pipeline {
    agent any

    tools { nodejs "nodejs" }
    stages {
        stage('Install NPM') { 
            steps {
                sh 'cd hello-react && npm install'
            }
        }
        stage('Build') {
            steps {
                sh 'cd hello-react && npm build'
            }
        }
    }
}
