pipeline {
    agent any

    tools {nodejs "node"}
    
    stages {
        stage('Install NPM') { 
            steps {
                sh 'cd hello-react && npm install'
            }
        }
        stage('Build') {
            steps {
                sh 'cd hello-react && npm run build'
            }
        }
        stage('Verify') {
            steps {
                sh 'cd hello-react && ls'
            }
        }
    }
}
