pipeline {
    agent any

    tools {nodejs "node"}
    
    stages {
        stage('Dir') {
            steps {
                sh 'cd hello-react'
            }
        }
        stage('Install NPM') { 
            steps {
                sh 'npm install'
            }
        }
        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }
        stage('Verify') {
            steps {
                sh 'ls'
            }
        }
    }
}
